### ISSUE TITLE
error on first request of viewvc-standalone

### ISSUE THREAD

**Issue by peterdd** [viewvc/viewvc#195] opened 2019-06-12 15:33 UTC
On the first request to viewvc-standalone the response shows an error in web browser.
Further reloads seem to be normal.
I have not yet setup any cvs ord svn repositories btw.

```
An Exception Has Occurred

An illegal parameter name was provided.
HTTP Response Status

400 Bad Request
```

The  request http header browser firefox sent (taken from firefox devtools):

```
Host: 10.0.0.31:49152
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```

The response http header the browser received (taken from firefox devtools):

```
HTTP/1.0 400 Bad Request
Server: BaseHTTP/0.3 Python/2.7.16
Date: Wed, 12 Jun 2019 15:25:23 GMT
Content-type: text/html
```

I just tried with a debian 10 buster vagrant image in vagrant+virtualbox machine

Here some info to help reproduce:

```bash
root@buster:~# apt install viewvc cvsgraph
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cvsgraph is already the newest version (1.7.0-5).
viewvc is already the newest version (1.1.26-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@buster:~# head -8 /vagrant/Vagrantfile
Vagrant.configure("2") do |config|
 config.vm.box = "debian/buster64"
 config.vm.network "private_network", ip: "10.0.0.31"

 config.vm.provision "shell", inline: <<-SHELL
  #apt-get update
  #apt-get upgrade
  apt-get install -y nano git autoconf apache2 php php-mysql perl gettext mariadb-server make imagemagick
root@buster:~# viewvc-standalone --host=10.0.0.31
server ready at http://10.0.0.31:49152/viewvc
10.0.0.1 - - [12/Jun/2019 15:17:07] "GET /viewvc HTTP/1.1" 400 -
10.0.0.1 - - [12/Jun/2019 15:17:07] ViewVC exited ok
10.0.0.1 - - [12/Jun/2019 15:17:28] "GET /viewvc HTTP/1.1" 200 -
10.0.0.1 - - [12/Jun/2019 15:17:28] ViewVC exited ok
10.0.0.1 - - [12/Jun/2019 15:17:28] "GET /viewvc/*docroot*/styles.css HTTP/1.1" 304 -
10.0.0.1 - - [12/Jun/2019 15:17:28] ViewVC exited ok
10.0.0.1 - - [12/Jun/2019 15:17:28] "GET /viewvc/*docroot*/images/viewvc-logo.png HTTP/1.1" 304 -
10.0.0.1 - - [12/Jun/2019 15:17:28] ViewVC exited ok
```

**Comment by cmpilato** [comment] 2019-06-27 13:15
I cannot reproduce this behavior locally with the latest ViewVC code from `master`, `1.1.x`, or `1.0.x`, with either a completely configured `viewvc.conf` or the default one (the copy of `viewvc.conf.dist`).

**Comment by cmpilato** [comment] 2019-06-27 13:19
Maybe something specific to the OS package?

**Comment by cmpilato** [comment] 2019-06-27 13:21
I'm going to close this, but feel free to reopen if you (or anyone) can add info to the discussion that can lead to a fix.

**Comment by peterdd** [comment] 2019-06-27 14:02
Problem still exists regardless which version. This time I tried with an opensuse15 vagrant box and tried the 
1) 1.1.26 version that came with opensuse
2) the latest release 1.1.27
3) with

 master

```
/home/vagrant # wget https://github.com/viewvc/viewvc/archive/master.zip
/home/vagrant # unzip master.zip
/home/vagrant # python -V
Python 2.7.14
/home/vagrant # ./viewvc-master/bin/standalone.py --host=10.0.0.10
server ready at http://10.0.0.10:49152/viewvc
10.0.0.1 - - [27/Jun/2019 15:52:28] "GET /viewvc HTTP/1.1" 400 -
10.0.0.1 - - [27/Jun/2019 15:52:28] ViewVC exited ok
10.0.0.1 - - [27/Jun/2019 15:52:34] "GET /viewvc HTTP/1.1" 200 -
10.0.0.1 - - [27/Jun/2019 15:52:34] ViewVC exited ok
```
![viewvc_bug](https://user-images.githubusercontent.com/1839154/60272570-bb1a0e80-98f4-11e9-8b6a-dacd48f6c483.png)

**Comment by cmpilato** [comment] 2019-06-27 16:08
But ... but ... but ... there were no parameters specified!

Are you able to tweak the viewvc.py module as follows to try to determine which "parameter" is causing the problem?

```
--- a/lib/viewvc.py
+++ b/lib/viewvc.py
@@ -630,7 +630,7 @@ def _validate_param(name, value):
     validator = _legal_params[name]
   except KeyError:
     raise debug.ViewVCException(
-      'An illegal parameter name was provided.',
+      'An illegal parameter name (%s) was provided.' % (name),
       '400 Bad Request')
 
   # Is there a validator?  Is it a regex or a function?  Validate if
```

**Comment by peterdd** [comment] 2019-06-27 21:01
An illegal parameter name (--host) was provided.

**Comment by cmpilato** [comment] 2019-06-28 12:25
Ah!  So the use of the `--host` standalone.py parameter is relevant to the recipe.  Didn't see that coming, yet I can confirm the issue now.

**Comment by cmpilato** [comment] 2019-06-28 12:58
I think I've figured out what's happening here.  standalone.py uses a server model that's based on `sapi.CgiServer`,  which in turn uses the Python `cgi.parse()` function to read CGI parameters.  `cgi.parse()` has an _undocumented_ behavior that if it can't find CGI parameters in a file object (such as `sys.stdin`) or in the CGI environment variables, it will uses `sys.argv[1:]`!  So in this case, `cgi.parse()` is using the parameters passed to standalone.py as if they were inbound CGI request parameters.

**Comment by cmpilato** [comment] 2019-06-28 13:04
Oops.  I committed before submitting my explanatory comment.  Oh, well.  I think this is fixed now.

@peterdd As a workaround, try using the syntax without the equal signs:  `--host 10.0.0.10`.  That seemed to help on my end (because it confuses `cgi.parse()`).

**Closed by cmpilato** 2019-06-28 13:04 UTC
Labels: invalid
