### ISSUE TITLE
ViewVC chokes on non-ASCII Subversion repository root name [Tigris #500]

### ISSUE THREAD

**Issue by cmpilato** [viewvc/viewvc#109] opened 2016-09-14 20:38 UTC
## Description

```
On systems with repository roots whose directory names contain non-ASCII
characters (say, for example, a UTF-8 Japanese string), ViewVC will fail to
correctly convert the path into UTF-8 as required by Subversion's API.
```
## Metadata Imported from Tigris (Issue 500)
- **Creation Date**: 2011-11-14 11:13:31
- **Reporter**: cmpilato
- **Subcomponent**: core
- **Version**: 1.1.12
- **Milestone**: _unscheduled_
- **Keywords**: patch
- **Cc**: 
### 2011-11-14 11:16:25 by cmpilato

```
Created an attachment (id=256)
Not-fully-tested patch for this issue
```
### 2011-11-14 14:06:59 by cmpilato

```
Created an attachment (id=257)
Not-fully-tested patch for this issue (v2)
```
### 2011-11-28 08:49:03 by cmpilato

```
This would be less tedious, I think, if 'viewvc-install' (which is less likely
to be running in a "C"-locale shell) would query the system's locale and
populate the appropriate configuration bits.
```
### issue-500-patch.txt - Not-fully-tested patch for this issue

_Posted 2011-11-14 11:16:25 by cmpilato_

```
Fix issue #500 ("ViewVC chokes on non-ASCII Subversion repository root
name").

* conf/viewvc.conf.dist
  (general.locale): New.

* lib/config.py
  (Config.set_defaults): Set default value for general.locale (to None).

* bin/asp/query.asp,
* bin/asp/viewvc.asp,
* bin/cgi/query.cgi,
* bin/cgi/viewvc.cgi,
* bin/cvsdbadmin,
* bin/loginfo-handler,
* bin/mod_python/query.py,
* bin/mod_python/viewvc.py,
* bin/standalone.py,
* bin/svndbadmin,
* bin/wsgi/query.wsgi,
* bin/wsgi/viewvc.fcgi,
* bin/wsgi/viewvc.wsgi
  After fetching the Config object, call locale.setlocale() to dictate
  any configured locale.
--This line, and those below, will be ignored--

Index: conf/viewvc.conf.dist
===================================================================
--- conf/viewvc.conf.dist   (revision 2670)
+++ conf/viewvc.conf.dist   (working copy)
@@ -197,6 +197,17 @@
 ##
 #address =

+## locale: Specifies the server's system locale.  This helps ViewVC
+## know how to interact with your server, for example when it needs to
+## convert between its internal path encoding and the encoding used on
+## your system.
+##
+## Examples:
+## locale = en_US.UTF-8
+## locale = Russian_Russia.1251
+##
+#locale = 
+
 ## kv_files: Provides a mechanism for custom key/value pairs to be
 ## available to templates.  These are stored in key/value (KV) files.
 ##
Index: lib/config.py
===================================================================
--- lib/config.py   (revision 2670)
+++ lib/config.py   (working copy)
@@ -382,6 +382,7 @@
     self.general.address = ''
     self.general.kv_files = [ ]
     self.general.languages = ['en-us']
+    self.general.locale = None

     self.utilities.rcs_dir = ''
     if sys.platform == "win32":
Index: bin/standalone.py
===================================================================
--- bin/standalone.py   (revision 2670)
+++ bin/standalone.py   (working copy)
@@ -422,6 +422,9 @@
 def handle_config(config_file):
   global cfg
   cfg = viewvc.load_config(config_file or CONF_PATHNAME)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)


 def usage():
Index: bin/mod_python/viewvc.py
===================================================================
--- bin/mod_python/viewvc.py    (revision 2670)
+++ bin/mod_python/viewvc.py    (working copy)
@@ -55,6 +55,9 @@
 def index(req):
   server = sapi.ModPythonServer(req)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   try:
     viewvc.main(server, cfg)
   finally:
Index: bin/mod_python/query.py
===================================================================
--- bin/mod_python/query.py (revision 2670)
+++ bin/mod_python/query.py (working copy)
@@ -61,6 +61,9 @@
     fp.close()

 cfg = viewvc.load_config(CONF_PATHNAME)
+if cfg.general.locale is not None:
+  import locale
+  locale.setlocale(locale.LC_ALL, cfg.general.locale)

 def index(req):
   server = sapi.ModPythonServer(req)
Index: bin/asp/viewvc.asp
===================================================================
--- bin/asp/viewvc.asp  (revision 2670)
+++ bin/asp/viewvc.asp  (working copy)
@@ -58,6 +58,9 @@
 server = sapi.AspServer(Server, Request, Response, Application)
 try:
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc.main(server, cfg)
 finally:
   s.close()
Index: bin/asp/query.asp
===================================================================
--- bin/asp/query.asp   (revision 2670)
+++ bin/asp/query.asp   (working copy)
@@ -54,6 +54,9 @@
 server = sapi.AspServer(Server, Request, Response, Application)
 try:
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc_base_url = cfg.query.viewvc_base_url
   if viewvc_base_url is None:
     viewvc_base_url = "viewvc.asp"
Index: bin/svndbadmin
===================================================================
--- bin/svndbadmin  (revision 2670)
+++ bin/svndbadmin  (working copy)
@@ -239,6 +239,9 @@

 def main(command, repository, revs=[], verbose=0, force=0):
     cfg = viewvc.load_config(CONF_PATHNAME)
+    if cfg.general.locale is not None:
+        import locale
+        locale.setlocale(locale.LC_ALL, cfg.general.locale)
     db = cvsdb.ConnectDatabase(cfg)

     # Purge what must be purged.
Index: bin/cgi/viewvc.cgi
===================================================================
--- bin/cgi/viewvc.cgi  (revision 2670)
+++ bin/cgi/viewvc.cgi  (working copy)
@@ -58,4 +58,7 @@

 server = sapi.CgiServer()
 cfg = viewvc.load_config(CONF_PATHNAME, server)
+if cfg.general.locale is not None:
+  import locale
+  locale.setlocale(locale.LC_ALL, cfg.general.locale)
 viewvc.main(server, cfg)
Index: bin/cgi/query.cgi
===================================================================
--- bin/cgi/query.cgi   (revision 2670)
+++ bin/cgi/query.cgi   (working copy)
@@ -54,6 +54,9 @@

 server = sapi.CgiServer()
 cfg = viewvc.load_config(CONF_PATHNAME, server)
+if cfg.general.locale is not None:
+  import locale
+  locale.setlocale(locale.LC_ALL, cfg.general.locale)
 viewvc_base_url = cfg.query.viewvc_base_url
 if viewvc_base_url is None:
   viewvc_base_url = "viewvc.cgi"
Index: bin/loginfo-handler
===================================================================
--- bin/loginfo-handler (revision 2670)
+++ bin/loginfo-handler (working copy)
@@ -221,6 +221,9 @@

 def ProcessLoginfo(rootpath, directory, files):
     cfg = viewvc.load_config(CONF_PATHNAME)
+    if cfg.general.locale is not None:
+        import locale
+        locale.setlocale(locale.LC_ALL, cfg.general.locale)
     db = cvsdb.ConnectDatabase(cfg)
     repository = vclib.ccvs.CVSRepository(None, rootpath, None,
                                           cfg.utilities, 0)
Index: bin/wsgi/viewvc.fcgi
===================================================================
--- bin/wsgi/viewvc.fcgi    (revision 2670)
+++ bin/wsgi/viewvc.fcgi    (working copy)
@@ -44,6 +44,9 @@
 def application(environ, start_response):
   server = sapi.WsgiServer(environ, start_response)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc.main(server, cfg)
   return []

Index: bin/wsgi/viewvc.wsgi
===================================================================
--- bin/wsgi/viewvc.wsgi    (revision 2670)
+++ bin/wsgi/viewvc.wsgi    (working copy)
@@ -37,5 +37,8 @@
 def application(environ, start_response):
   server = sapi.WsgiServer(environ, start_response)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc.main(server, cfg)
   return []
Index: bin/wsgi/query.wsgi
===================================================================
--- bin/wsgi/query.wsgi (revision 2670)
+++ bin/wsgi/query.wsgi (working copy)
@@ -38,6 +38,9 @@
 def application(environ, start_response):
   server = sapi.WsgiServer(environ, start_response)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc_base_url = cfg.query.viewvc_base_url
   if viewvc_base_url is None:
     viewvc_base_url = "viewvc.wsgi"
Index: bin/cvsdbadmin
===================================================================
--- bin/cvsdbadmin  (revision 2670)
+++ bin/cvsdbadmin  (working copy)
@@ -171,6 +171,9 @@
     rootpath = vclib.ccvs.canonicalize_rootpath(root)
     try:
         cfg = viewvc.load_config(CONF_PATHNAME)
+        if cfg.general.locale is not None:
+            import locale
+            locale.setlocale(locale.LC_ALL, cfg.general.locale)
         db = cvsdb.ConnectDatabase(cfg)

         if command in ('rebuild', 'purge'):
```
### issue-500-patch.2.txt - Not-fully-tested patch for this issue (v2)

_Posted 2011-11-14 14:06:58 by cmpilato_

```
Fix issue #500 ("ViewVC chokes on non-ASCII Subversion repository root
name").

* conf/viewvc.conf.dist
  (general.locale): New.

* lib/config.py
  (Config.set_defaults): Set default value for general.locale (to None).

* bin/asp/query.asp,
* bin/asp/viewvc.asp,
* bin/cgi/query.cgi,
* bin/cgi/viewvc.cgi,
* bin/cvsdbadmin,
* bin/loginfo-handler,
* bin/mod_python/query.py,
* bin/mod_python/viewvc.py,
* bin/standalone.py,
* bin/svndbadmin,
* bin/wsgi/query.wsgi,
* bin/wsgi/viewvc.fcgi,
* bin/wsgi/viewvc.wsgi
  After fetching the Config object, call locale.setlocale() to dictate
  any configured locale.
--This line, and those below, will be ignored--

Index: conf/viewvc.conf.dist
===================================================================
--- conf/viewvc.conf.dist   (revision 2670)
+++ conf/viewvc.conf.dist   (working copy)
@@ -197,6 +197,17 @@
 ##
 #address =

+## locale: Specifies the server's system locale.  This helps ViewVC
+## know how to interact with your server, for example when it needs to
+## convert between its internal path encoding and the encoding used on
+## your system.
+##
+## Examples:
+## locale = en_US.UTF-8
+## locale = Russian_Russia.1251
+##
+#locale = 
+
 ## kv_files: Provides a mechanism for custom key/value pairs to be
 ## available to templates.  These are stored in key/value (KV) files.
 ##
Index: lib/config.py
===================================================================
--- lib/config.py   (revision 2670)
+++ lib/config.py   (working copy)
@@ -382,6 +382,7 @@
     self.general.address = ''
     self.general.kv_files = [ ]
     self.general.languages = ['en-us']
+    self.general.locale = None

     self.utilities.rcs_dir = ''
     if sys.platform == "win32":
Index: bin/standalone.py
===================================================================
--- bin/standalone.py   (revision 2670)
+++ bin/standalone.py   (working copy)
@@ -422,6 +422,9 @@
 def handle_config(config_file):
   global cfg
   cfg = viewvc.load_config(config_file or CONF_PATHNAME)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)


 def usage():
Index: bin/mod_python/viewvc.py
===================================================================
--- bin/mod_python/viewvc.py    (revision 2670)
+++ bin/mod_python/viewvc.py    (working copy)
@@ -55,6 +55,9 @@
 def index(req):
   server = sapi.ModPythonServer(req)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   try:
     viewvc.main(server, cfg)
   finally:
Index: bin/mod_python/query.py
===================================================================
--- bin/mod_python/query.py (revision 2670)
+++ bin/mod_python/query.py (working copy)
@@ -61,6 +61,9 @@
     fp.close()

 cfg = viewvc.load_config(CONF_PATHNAME)
+if cfg.general.locale is not None:
+  import locale
+  locale.setlocale(locale.LC_ALL, cfg.general.locale)

 def index(req):
   server = sapi.ModPythonServer(req)
Index: bin/asp/viewvc.asp
===================================================================
--- bin/asp/viewvc.asp  (revision 2670)
+++ bin/asp/viewvc.asp  (working copy)
@@ -58,6 +58,9 @@
 server = sapi.AspServer(Server, Request, Response, Application)
 try:
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc.main(server, cfg)
 finally:
   s.close()
Index: bin/asp/query.asp
===================================================================
--- bin/asp/query.asp   (revision 2670)
+++ bin/asp/query.asp   (working copy)
@@ -54,6 +54,9 @@
 server = sapi.AspServer(Server, Request, Response, Application)
 try:
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc_base_url = cfg.query.viewvc_base_url
   if viewvc_base_url is None:
     viewvc_base_url = "viewvc.asp"
Index: bin/svndbadmin
===================================================================
--- bin/svndbadmin  (revision 2670)
+++ bin/svndbadmin  (working copy)
@@ -239,6 +239,9 @@

 def main(command, repository, revs=[], verbose=0, force=0):
     cfg = viewvc.load_config(CONF_PATHNAME)
+    if cfg.general.locale is not None:
+        import locale
+        locale.setlocale(locale.LC_ALL, cfg.general.locale)
     db = cvsdb.ConnectDatabase(cfg)

     # Purge what must be purged.
Index: bin/cgi/viewvc.cgi
===================================================================
--- bin/cgi/viewvc.cgi  (revision 2670)
+++ bin/cgi/viewvc.cgi  (working copy)
@@ -58,4 +58,7 @@

 server = sapi.CgiServer()
 cfg = viewvc.load_config(CONF_PATHNAME, server)
+if cfg.general.locale is not None:
+  import locale
+  locale.setlocale(locale.LC_ALL, cfg.general.locale)
 viewvc.main(server, cfg)
Index: bin/cgi/query.cgi
===================================================================
--- bin/cgi/query.cgi   (revision 2670)
+++ bin/cgi/query.cgi   (working copy)
@@ -54,6 +54,9 @@

 server = sapi.CgiServer()
 cfg = viewvc.load_config(CONF_PATHNAME, server)
+if cfg.general.locale is not None:
+  import locale
+  locale.setlocale(locale.LC_ALL, cfg.general.locale)
 viewvc_base_url = cfg.query.viewvc_base_url
 if viewvc_base_url is None:
   viewvc_base_url = "viewvc.cgi"
Index: bin/loginfo-handler
===================================================================
--- bin/loginfo-handler (revision 2670)
+++ bin/loginfo-handler (working copy)
@@ -221,6 +221,9 @@

 def ProcessLoginfo(rootpath, directory, files):
     cfg = viewvc.load_config(CONF_PATHNAME)
+    if cfg.general.locale is not None:
+        import locale
+        locale.setlocale(locale.LC_ALL, cfg.general.locale)
     db = cvsdb.ConnectDatabase(cfg)
     repository = vclib.ccvs.CVSRepository(None, rootpath, None,
                                           cfg.utilities, 0)
Index: bin/wsgi/viewvc.fcgi
===================================================================
--- bin/wsgi/viewvc.fcgi    (revision 2670)
+++ bin/wsgi/viewvc.fcgi    (working copy)
@@ -44,6 +44,9 @@
 def application(environ, start_response):
   server = sapi.WsgiServer(environ, start_response)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc.main(server, cfg)
   return []

Index: bin/wsgi/query.fcgi
===================================================================
--- bin/wsgi/query.fcgi (revision 2670)
+++ bin/wsgi/query.fcgi (working copy)
@@ -45,6 +45,9 @@
 def application(environ, start_response):
   server = sapi.WsgiServer(environ, start_response)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc_base_url = cfg.query.viewvc_base_url
   if viewvc_base_url is None:
     viewvc_base_url = "viewvc.fcgi"
Index: bin/wsgi/viewvc.wsgi
===================================================================
--- bin/wsgi/viewvc.wsgi    (revision 2670)
+++ bin/wsgi/viewvc.wsgi    (working copy)
@@ -37,5 +37,8 @@
 def application(environ, start_response):
   server = sapi.WsgiServer(environ, start_response)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc.main(server, cfg)
   return []
Index: bin/wsgi/query.wsgi
===================================================================
--- bin/wsgi/query.wsgi (revision 2670)
+++ bin/wsgi/query.wsgi (working copy)
@@ -38,6 +38,9 @@
 def application(environ, start_response):
   server = sapi.WsgiServer(environ, start_response)
   cfg = viewvc.load_config(CONF_PATHNAME, server)
+  if cfg.general.locale is not None:
+    import locale
+    locale.setlocale(locale.LC_ALL, cfg.general.locale)
   viewvc_base_url = cfg.query.viewvc_base_url
   if viewvc_base_url is None:
     viewvc_base_url = "viewvc.wsgi"
Index: bin/cvsdbadmin
===================================================================
--- bin/cvsdbadmin  (revision 2670)
+++ bin/cvsdbadmin  (working copy)
@@ -171,6 +171,9 @@
     rootpath = vclib.ccvs.canonicalize_rootpath(root)
     try:
         cfg = viewvc.load_config(CONF_PATHNAME)
+        if cfg.general.locale is not None:
+            import locale
+            locale.setlocale(locale.LC_ALL, cfg.general.locale)
         db = cvsdb.ConnectDatabase(cfg)

         if command in ('rebuild', 'purge'):
```

**Comment by futatuki** [comment] 2020-04-01 06:48
At leaset on Python 3 (say, in master),  we should decide which encoding to read viewvc.conf, because `configparser.ConfigParser` reads cvs_root or svn_root path items as `str`. 
Then Python or modules for CVS or Subversion interpret paths in `str` to paths on file systems (arbitrary asciiz sequence separated by `'/'` in traditional file systems on Unix like systems), by specified encodings (by locale environment variable or locale setting in conf file?).

Anyways, I can access utf-8 encoded repository path in current master code by using `LANG=ja_JP.utf-8` and following repository setting, using utf-8 for viewvc.conf:

    `svn_roots = utf8-dir-repo: /home/futatuki/tmp/svn-test/日本語テストディレクトリ/trac-unittest-repo`

("日本語テストディレクトリ" means "Japanese language test directory", in Japanese language.)

**Comment by cmpilato** [comment] 2021-05-10 16:51
I lean towards reading the configuration files as UTF-8.  It would be convenient to declare that ViewVC expects to be hosted on a machine that uses the same as its locale (for interactions with the filesystem, etc.) but I don't think we can be so demanding.  So maybe we need to employ the `locale.setlocale()` methods as demonstrated by the patch?

**Comment by futatuki** [comment] 2021-05-10 18:31
As configparser.ConfigParser.read() on Python 2 read a config file as bytes stream,  we could determine the encoding of items in configfile after read them.  However, unfortunately, configparser.ConfigParser.read() on Python 3 reads a whole config file in specified encoding (or default encoding decided on starting Python interpreter), and if the file contains character that cannot decode as the specified encoding,  the parser raise `UnicodeDecodeError`.

So we can't specify the encoding to decode the config file with in the same config file, if we want to use configparser.ConfigParser as is.

**Comment by cmpilato** [comment] 2021-05-10 18:45
If Python2 reads config files as a bytestream and we've never done anything to try to interpret that stream in a locale-specific way before, can we not assume that extant viewvc.conf files likely contain only ASCII content?  And if we can make that assumption, then I'm okay with saying now and going forward that configuration files are UTF-8 (a superset of ASCII).  Nothing "meta" to be concerned about, just UTF-8.

Of course, if we have reason to believe that there are ViewVC 1.2 or older installations with viable and meaningful non-ASCII data in their configuration files, then we have to consider this more deeply.

**Comment by futatuki** [comment] 2021-05-10 18:48
Ah, sorry I misunderstanding a bit.  Is your idea that  read it in UTF-8 and decode to Unicode, and then check the locale option and transcode the path into locale encoding, right?

**Comment by cmpilato** [comment] 2021-05-10 18:58
Yes, that's what I meant.  Sorry for being unclear.

**Comment by futatuki** [comment] 2022-10-24 11:55
For CVS repos on Unix/Linux,  changing locale does not resolve the issue,  because Python always encodes str paths by internal file system encoding,  which is determined at start up and cannot change while running the program(in normal way).

We should encode paths into bytes in the `lib/vclib/ccvs` module when open files or execute external programs on Unix/Linux, but should not on Windows.

**Comment by futatuki** [comment] 2022-10-24 18:16
I confirmed that the current code in master(a2054e278a9f79f1e3be0b500af8a60a5ae4c9d9) cannot handle file names other than UTF-8/ascii encoding in CVS repos, even if set the appropriate LC_CTYPE locale on server start up and set appropriate `default_encoding` option, both in `use_rcsparse = 0` and in `use_rcsparse = 1` case.

**Comment by futatuki** [comment] 2022-10-25 09:07
@cmpilato How do you think about paths of external utilities, like `diff` and `rcs` on POSIX system?  Should we add general parameters per utility for the encodings of their paths?

They can be placed the path contains non-ascii characters.  Especially we use `rcs` with RCS file paths which can contain characters of different encoding  from the encoding of the `rcs` utility path, but perhaps it can work because `rcs` utility doesn't care the path encoding, it only handles the path as asciiz string, in a wide sense.

**Comment by cmpilato** [comment] 2022-10-25 12:42
We can add whatever configuration makes sense.  I would like to avoid, through, having different pieces of ViewVC code having to be aware of all these things.  Is there some way to write individual wrapper methods for each external utility (`call_external_diff()`) that communicate solely in (unicode) `str`s but are internally aware of the utility's path encoding, the system locale, the encoding of any path arguments to the utility, etc.?  I don't want multiple pieces of code having to think about these things and scattered throughout the system if possible.

Also, every new configuration item is something that _someone_ has to think about (generally package maintainers in our ecosystem), so we must choose great defaults.  The 1.3.0 release affords an opportunity to completely rearrange our configuration "namespace" if we need to.

**Comment by futatuki** [comment] 2022-10-25 15:46
It is reasonable that we assume that encoding of the utilitie's path are always determined by the system locale or the locale explicitly specified in locale environent variable, which is "file system encoding" in Python.  Even if the case it isn't,  user may make symlinks for those utilities.

> Is there some way to write individual wrapper methods for each external utility (call_external_diff()) that communicate solely in (unicode) strs but are internally aware of the utility's path encoding, the system locale, the encoding of any path arguments to the utility, etc.? I don't want multiple pieces of code having to think about these things and scattered throughout the system if possible.

Fortunately, '`diff`', '`rcs`', '`cvsnt`' have already wrapper methods deep in `lib/vclib`. '`cvsgraph`' doesn't have the wrapper method yet,  but it should be in lib/ccvs module, (as a method in `BaseCVSRepository` class?).

**Comment by futatuki** [comment] 2022-10-28 16:12
Now I make a draft PR #299, for preview and testing.

**Comment by futatuki** [comment] 2022-11-30 15:34
PR #299 had merged, and the issue was resolved. Close.

**Closed by futatuki** 2022-11-30 15:34 UTC
Labels: bug, patch
