### ISSUE TITLE
TypeError in diff view of viewvc 1.3.0 master if hr_intraline is set

### ISSUE THREAD

**Issue by NMGo** [viewvc/viewvc#275] opened 2022-01-10 16:04 UTC
**_Edit 2_: looks like the exceptions are thrown only when hr_intraline is set.**

Recently, we upgraded a Subversion installation to 1.14.1 on a CentOS 7 server.

From what we can tell, Subversion 1.14.1 no longer has bindings for Python 2 meaning we had to switch to the development branch ("master") of ViewVC 1.3.0 at commit f97ea61 of Dec 1, 2021.

Everything appears to be working except the "diff" views where we're seeing the following error when checking the changes to a text file using a "colored diff":
```
An Exception Has Occurred
Python Traceback
TypeError: a bytes-like object is required, not 'str'
```
A "unidiff" is also broken but the error is different (the reverse?):
```
An Exception Has Occurred
Python Traceback
TypeError: must be str, not bytes
```

Diff views in "context diff" and "side by side" don't throw an exception but are much harder to parse by a person, of course.

Pygments is installed:
```
# pip3 show Pygments | grep Version
Version: 2.2.0
#
```

We don't know if this is a known issue with ViewVC 1.3.0 or if we have a missing dependency.

_Edit 1_: below are the system details as requested by @futatuki.
CentOS  7.9.2009, Apache 2.4.6, Python 3.6.8, Pygments 2.2.0, GNU diffutils 3.3, Subversion 1.14.1
```
[general]
root_parents = /var/svn/repos: svn
[utilities]
diff = /usr/bin/diff
[options]
allowed_views = annotate, diff, markup, roots, tar
authorizer = svnauthz
custom_log_formatting =
  bug ([0-9]+) : https://its.site.tld/browse/BGZ-\1,
  ([A-Z]+\-[0-9]+) : https://its.site.tld/browse/\1,
  \[([3-7]{1}[0-9]{3})\] : https://its.site.tld/browse/BGZ-\1,
  (rev|revs)\.\s*([0-9]+) : https://svn.site.tld/viewvc/repo?view=revision&revision=\2
default_file_view = markup
max_filesize_kbytes = 1024
log_sort = none
hr_intraline = 1
template_dir = templates/classic
docroot = /viewvc/static
enable_syntax_coloration = 1
tabsize = 0
log_pagesize = 75
log_pagesextra = 10
[templates]
[cvsdb]
[vhosts]
[authz-forbidden]
[authz-forbiddenre]
[authz-svnauthz]
authzfile = /var/svn/etc/svnaccessfile
```

**Comment by futatuki** [comment] 2022-01-10 17:47
I cannot reproduce it in my environment, FreeBSD 13, Python 3.9.8, Pygments 2.7.2, GNU diff 3.8, with standalone server.

My viewvc.conf:
```
[general]
cvs_roots = irregular-rcs-test: /home/cvs/irregular-rcs-test
svn_roots = test_repo: /home/futatuki/tmp/svn-test/testrepo,
            svn_cython: /home/futatuki/tmp/svn-test/svn_cython,
            (ommit some repos for privacy)
            bad-utf8-test: /home/futatuki/tmp/svn-test/bad-utf8-test
[utilities]
diff = /usr/local/bin/gdiff
[options]
allowed_views = annotate, co, diff, markup, roots, tar
use_rcsparse = 1
stacktraces = 1
[templates]
[cvsdb]
[vhosts]
[authz-forbidden]
[authz-forbiddenre]
[authz-svnauthz]

```

Could you tell us about your environment in detail?

P.S.
> Subversion 1.14.1 no longer has bindings for Python 2

It is not correct.  Subversion 1.14.x still supports Python 2 bindings, although it needs SWIG and extra steps for building. I also personally provide a Subversion 1.14.x package for el7 with both of Python 2 and Python 3 bindings, on https://mm.poem.co.jp/misc.html (but no warranty).

**Comment by futatuki** [comment] 2022-01-10 17:57
> I cannot reproduce it 

... however, I found "full color diff" does not work correctly in my environment. It shows "- No changes -" even other formats show changes.

**Comment by NMGo** [comment] 2022-01-10 18:24
> Could you tell us about your environment in detail?
Thanks for looking into this, @futatuki. I have edited by original post above with the system details and the stripped down ViewCS configuration file.

> > Subversion 1.14.1 no longer has bindings for Python 2
> 
> It is not correct. Subversion 1.14.x still supports Python 2 bindings, although it needs SWIG and extra steps for building. I also personally provide a Subversion 1.14.x package for el7 with both of Python 2 and Python 3 bindings, on https://mm.poem.co.jp/misc.html (but no warranty).
Thanks for the link to your site. We will be reviewing the information.

**Comment by NMGo** [comment] 2022-01-10 18:44
Just noticed @futatuki is using the "stacktraces" option.

Here's the full "trackback" for the "colored" diffs:
```
Python Traceback
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 5521, in main
    request.run_viewvc()
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 457, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 4117, in view_diff
    generate_page(request, "diff", data)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 1024, in generate_page
    template.generate(server_fp, data)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 347, in generate
    self._execute(self.program, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 582, in _cmd_if_any
    self._do_if(value, t_section, f_section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 615, in _do_if
    self._execute(section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 625, in _cmd_for
    self._execute(section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 604, in _cmd_is
    self._do_if(value, t_section, f_section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 615, in _do_if
    self._execute(section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 624, in _cmd_for
    for item in list:
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/idiff.py", line 32, in sidebyside
    fromlines = list(map(_stripnl, fromlines))
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/idiff.py", line 30, in _stripnl
    return line.rstrip("\n")
TypeError: a bytes-like object is required, not 'str'
```

We had to switch to the "default" template to get the stacktraces option to work.

For the "unidiff" view, the full traces are as follows:
```
Python Traceback
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 5521, in main
    request.run_viewvc()
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 457, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 4117, in view_diff
    generate_page(request, "diff", data)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 1024, in generate_page
    template.generate(server_fp, data)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 347, in generate
    self._execute(self.program, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 582, in _cmd_if_any
    self._do_if(value, t_section, f_section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 615, in _do_if
    self._execute(section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 625, in _cmd_for
    self._execute(section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 604, in _cmd_is
    self._do_if(value, t_section, f_section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 615, in _do_if
    self._execute(section, fp, ctx)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/ezt.py", line 624, in _cmd_for
    for item in list:
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/idiff.py", line 86, in unified
    for row in _trim_context(diff, context):
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/idiff.py", line 123, in _trim_context
    for line in lines:
  File "/usr/lib64/python3.6/difflib.py", line 907, in compare
    yield from g
  File "/usr/lib64/python3.6/difflib.py", line 1014, in _fancy_replace
    yield from self._qformat(aelt, belt, atags, btags)
  File "/usr/lib64/python3.6/difflib.py", line 1059, in _qformat
    yield "- " + aline
TypeError: must be str, not bytes
```

**Comment by NMGo** [comment] 2022-01-10 19:03
Looks like hr_intraline needs to be set to reproduce the errors. I've edited my original post once more.

**Comment by futatuki** [comment] 2022-01-10 19:59
> Looks like hr_intraline needs to be set to reproduce the errors. I've edited my original post once more.

Thank you for finding out it. With `hr_intraline = 1`, I can reproduce the issue in "full color diff".  However,  in "unidiff" view, I got another exception:
```
  File "/home/futatuki/work/viewvc/lib/viewvc.py", line 5521, in main
    request.run_viewvc()
  File "/home/futatuki/work/viewvc/lib/viewvc.py", line 457, in run_viewvc
    self.view_func(self)
  File "/home/futatuki/work/viewvc/lib/viewvc.py", line 4117, in view_diff
    generate_page(request, "diff", data)
  File "/home/futatuki/work/viewvc/lib/viewvc.py", line 1024, in generate_page
    template.generate(server_fp, data)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 347, in generate
    self._execute(self.program, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 582, in _cmd_if_any
    self._do_if(value, t_section, f_section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 615, in _do_if
    self._execute(section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 625, in _cmd_for
    self._execute(section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 604, in _cmd_is
    self._do_if(value, t_section, f_section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 615, in _do_if
    self._execute(section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 624, in _cmd_for
    for item in list:
  File "/home/futatuki/work/viewvc/lib/idiff.py", line 86, in unified
    for row in _trim_context(diff, context):
  File "/home/futatuki/work/viewvc/lib/idiff.py", line 123, in _trim_context
    for line in lines:
  File "/usr/local/lib/python3.9/difflib.py", line 872, in compare
    yield from g
  File "/usr/local/lib/python3.9/difflib.py", line 979, in _fancy_replace
    yield from self._qformat(aelt, belt, atags, btags)
  File "/usr/local/lib/python3.9/difflib.py", line 1015, in _qformat
    atags = _keep_original_ws(aline, atags).rstrip()
  File "/usr/local/lib/python3.9/difflib.py", line 717, in _keep_original_ws
    return ''.join(
  File "/usr/local/lib/python3.9/difflib.py", line 718, in <genexpr>
    c if tag_c == " " and c.isspace() else tag_c
AttributeError: 'int' object has no attribute 'isspace'
```
but it seems the root cause of the exception is same.

I'll investigate it.

**Comment by futatuki** [comment] 2022-01-15 16:50
The root cause of this issue is ambiguous specification of DiffDescription._get_diff() interface: `get_lines` is a function to obtain a list of strings, and `get_fp` is a function to obtain a IOstream.  However when I rewrote for Python 3, I didn't determine explicitly which the IOstream and string are, bytes or str.

Perhaps they should be str, which might contain surrogate-escaped non-unicode sequences, for raw diff output (view=patch) needs it.

**Comment by sshock** [comment] 2022-07-25 07:17
Is this being worked on?  Is it a hard fix?

**Comment by futatuki** [comment] 2022-07-25 09:19
I'm sorry, but I've had no solid block of time to focus this issue since then.

**Comment by futatuki** [comment] 2022-10-12 04:45
> > I cannot reproduce it
> 
> ... however, I found "full color diff" does not work correctly in my environment. It shows "- No changes -" even other formats show changes.

This was another issue that caused by the change of behaviour on diff 3.8. I opend a new issue #293 for this.

**Comment by futatuki** [comment] 2022-10-15 09:51
> The root cause of this issue is ambiguous specification of DiffDescription._get_diff() interface: get_lines is a function to obtain a list of strings, and get_fp is a function to obtain a IOstream. However when I rewrote for Python 3, I didn't determine explicitly which the IOstream and string are, bytes or str.

In case `hr_intraline = 1`,  and diff format is "colored" or "unified", `DiffDescription._get_diff` uses only `get_lines` and it uses `idiff` module to get diffs.

The cause of `TypeError` was get_lines function returns a list of `bytes`,  instead of a list of `str`.  This will be fixed a patch below:

```
index 1bccb86a..2bf92475 100644
--- a/lib/viewvc.py
+++ b/lib/viewvc.py
@@ -4021,7 +4021,8 @@ class DiffDescription:
     def _content_lines(self, side, propname):
         f = self.request.repos.openfile(side.path_comp, side.rev, {})[0]
         try:
-            lines = f.readlines()
+            lines = [l.decode(self.request.repos.encoding,'surrogateescape')
+                     for l in f.readlines()]
         finally:
             f.close()
         return lines
@@ -4033,8 +4034,7 @@ class DiffDescription:
 
     def _prop_lines(self, side, propname):
         val = side.properties.get(propname, "")
-        # FIXME: dirty hack for Python 3: we need bytes as return value
-        return val.encode("utf-8", "surrogateescape").splitlines()
+        return val.splitlines()
 
     def _prop_fp(self, left, right, propname, diff_options):
         fn_left = self._temp_file(left.properties.get(propname))

```

However,  there still exists something wrong. It causes another exception like this.
```
  File "/home/futatuki/work/viewvc/lib/viewvc.py", line 5539, in main
    request.run_viewvc()
  File "/home/futatuki/work/viewvc/lib/viewvc.py", line 452, in run_viewvc
    self.view_func(self)
  File "/home/futatuki/work/viewvc/lib/viewvc.py", line 4138, in view_diff
    generate_page(request, "diff", data)
  File "/home/futatuki/work/viewvc/lib/viewvc.py", line 1019, in generate_page
    template.generate(server_fp, data)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 347, in generate
    self._execute(self.program, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 582, in _cmd_if_any
    self._do_if(value, t_section, f_section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 615, in _do_if
    self._execute(section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 625, in _cmd_for
    self._execute(section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 604, in _cmd_is
    self._do_if(value, t_section, f_section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 615, in _do_if
    self._execute(section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 625, in _cmd_for
    self._execute(section, fp, ctx)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 524, in _execute
    method(method_args, fp, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 602, in _cmd_is
    left_value = _get_value(left_ref, ctx, filename, line_number)
  File "/home/futatuki/work/viewvc/lib/ezt.py", line 710, in _get_value
    ob = list[idx]
TypeError: 'generator' object is not subscriptable
```

I'll continue reading the code....

**Closed** 2022-10-18 19:01 UTC
Labels: bug
