### ISSUE TITLE
freebsd 12-4 / viewvc / apache24 configuration

### ISSUE THREAD

**Issue by dw07dal** [viewvc/viewvc#321] opened 2023-03-22 09:20 UTC
Hi,

 I am new to freebsd, rancid, viewvc and apache24 configuration.

 I have configured Rancid which appears to be correct. I can see the directory tree has been created. I can log onto devices through Rancid, and Rancid has downloaded a device config.

 I can access viewvc through apache24 however there are two root directories (CVS, rancid) and only the top level rancid group folders are visible in each, no subdirectories or files are visible. When trying to access the subdirectories (Routers Switches Firewalls Wireless-Aps) I receive a 'python trackback' error.

 My configuration is based on the package install info, and minimal documentation and examples I can find on the internet.  I am stuck at the moment and can not find the information i need to progress.

 Please see my rc.conf config below and I have attached my configs for Rancid, Viewvc and Apache24. Any advice or assistance on how to progress would be greatly appreciated.

root@rancid:/etc # cat /etc/rc.conf
hostname="rancid"
keymap="uk.kbd"
ifconfig_em0="DHCP"
sshd_enable="YES"
moused_enable="YES"
moused_port="/dev/psm0"
moused_type="auto"
ntpdate_enable="YES"
ntpd_enable="YES"
vmware_guestd_enable="YES"
vmware_guest_kmod_enable="YES"
slim_enable="YES"
dbus_enable="YES"
viewvc_enable="YES"
apache24_enable="YES"
mysql_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
 

Regards

dw07

[Rancid directory tree and files.txt](https://github.com/viewvc/viewvc/files/11038324/Rancid.directory.tree.and.files.txt)
[Viewvc directory tree and files.txt](https://github.com/viewvc/viewvc/files/11038326/Viewvc.directory.tree.and.files.txt)
[Apache24 directory tree and files.txt](https://github.com/viewvc/viewvc/files/11038327/Apache24.directory.tree.and.files.txt)

**Comment by futatuki** [comment] 2023-03-22 09:46
Duplicate of #320

**Comment by futatuki** [comment] 2023-03-23 07:59
As this was discussed in #320, I close #321

**Closed by futatuki** 2023-03-23 07:59 UTC
Labels: help-needed
